version: '3.8'

services:

  api:
    build: .
    container_name: gerenciador-api

    environment:
      ASPNETCORE_URLS: "http://+:8080"
      JwtSettings__SecretKey: ${JWT_SECRET}

    ports:
      - "8080:8080"

    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver

    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${SA_PASSWORD}

    ports:
      - "1433:1433"

    volumes:
      - sql-data:/var/opt/mssql

volumes:
  sql-data: